import React from "react";
import "./home.scss";

export const Home = () => {
  return (
    <div className="home">
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
      <h1>home</h1>
    </div>
  );
};
